# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Subscription (cbb012e8-782b-48d9-a8fe-a45ab657780f)'
    subscriptionId: 'cbb012e8-782b-48d9-a8fe-a45ab657780f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azurekeyvault'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/AnatolyPalyony/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json?token=ABXW3GUFZLF6DTC7DASA2XDAJHNEO'
    overrideParameters: '-projectName DepKV1'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
